version: '3.7'

services:
  # Reverse Proxy Production version container
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    restart: "unless-stopped"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - network-backend

  # Local PostgreSQL database container
  db-postgres:
    container_name: db-postgres
    image: postgres:12
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - network-backend

  # Local Redis container
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis-local
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    # - Double dollars, so that the variable is not expanded by Docker Compose
    # - Surround by quotes, so that the shell does not split the password
    # - The ${variable:?message} syntax causes shell to exit with a non-zero
    #   code and print a message, when the variable is not set or empty
    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
        "--requirepass",
        "${REDIS_PASSWORD}"
      ]
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/acl/users.acl:/etc/redis/users.acl
    networks:
      - network-backend

# Docker Network
networks:
  network-backend:
    driver: bridge
    name: network-backend
