version: '3.7'

services:
  # Groomer Note Talk Server
  nestjs-app:
    container_name: nestjs-app
    restart: always
    image: qjqdn1568/potenday-308-nestjs-staging:latest
    environment:
      - NODE_ENV=test
      - SERVER_PORT=3000
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - network-backend

  # Reverse Proxy Production version container 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    restart: "unless-stopped"
    depends_on:
      - nestjs-app
    volumes:
      - ./nginx/nginx.staging.v1.conf:/etc/nginx/nginx.conf
    networks:
      - network-backend

  # Local PostgreSQL database container
  db-postgres:
    container_name: db-postgres
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=potenday_308_009_test
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_potenday_308_009_test
    expose:
      - 5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - network-backend

  # Local Redis container
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis-local
    ports:
      - 6379:6379
    # - Double dollars, so that the variable is not expanded by Docker Compose
    # - Surround by quotes, so that the shell does not split the password
    # - The ${variable:?message} syntax causes shell to exit with a non-zero
    #   code and print a message, when the variable is not set or empty
    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
        "--requirepass",
        "1234"
      ]
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/acl/users.acl:/etc/redis/users.acl
    networks:
      - network-backend

# Docker Network
networks:
  network-backend:
    driver: bridge
    name: network-backend
