export const EmploymentOpportunityInjector = {
  EMPLOYMENT_OPPORTUNITY_SERVICE: Symbol('EMPLOYMENT_OPPORTUNITY_SERVICE'),
  PERSONAL_STATEMENT_SERVICE: Symbol('PERSONAL_STATEMENT_SERVICE'),
} as const;
