export const AuthInjector = {
  REFRESH_TOKEN_SERVICE: Symbol('REFRESH_TOKEN_SERVICE'),
  ACCESS_TOKEN_SERVICE: Symbol('ACCESS_TOKEN_SERVICE'),
  BLACK_LIST_SERVICE: Symbol('BLACK_LIST_SERVICE'),
} as const;
